---

- name: "Tower Example Play"
  hosts: cisco_devices
  gather_facts: false
  connection: network_cli
  
  tasks:
    - name: "OSPF Config"
      cisco.ios.ios_config:
        lines:
          - "router-id {{ ospf_rid }}"
        parents:
          - "router ospf 1"
      register: my_output

    - name: "Display Output"
      debug:
        var: my_output
